const Jobdata = [
  {
    id: 1,
    Category: "Finance & Accounting",
    title: "Foreign Language Research Analyst (Chinese)",
    location: "Lagos",
    type: "full time",
    company: "Globe Solution Ltd.",
    logo: "/images/companies/company-logo1.svg",
    time: "5hrs ago",
    salary: "N100,000 - N150,000",
  },
  {
    id: 2,
    Category: "Creative & Art",
    title: "User Experience Designer - Employee Solutions",
    location: "Lagos",
    type: "full time",
    company: "Globe Solution Ltd.",
    logo: "/images/companies/company-logo2.svg",
    time: "5hrs ago",
    salary: "N150,000 - N200,000",
  },
  {
    id: 3,
    Category: "sales",
    title: "Sales Representative",
    location: "Abuja",
    type: "part time",
    company: "Globe Solution Ltd.",
    logo: "/images/companies/company-logo3.svg",
    time: "5hrs ago",
    salary: "confidential",
  },
  {
    id: 4,
    Category: "Customer Service & Support",
    title: "Call Centre Operator",
    location: "Enugu",
    type: "full time",
    company: "Globe Solution Ltd.",
    logo: "/images/companies/company-logo4.svg",
    time: "5hrs ago",
    salary: "N70,000 - N100,000",
  },
  {
    id: 5,
    Category: "Marketing & Communications",
    title: "Marketer",
    location: "Lagos",
    type: "full time",
    company: "Globe Solution Ltd Globe Solution Ltd.",
    logo: "/images/companies/company-logo5.svg",
    time: "5hrs ago",
    salary: "N50,000 - N70,000",
  },
  {
    id: 6,
    Category: "Marketing & Communications",
    title: "Senior Finance Officer (with USAID experience)",
    location: "Lagos",
    type: "full time",
    company: "Globe Solution Ltd.",
    logo: "/images/companies/company-logo6.svg",
    time: "5hrs ago",
    salary: "confidential",
  },
];
export default Jobdata;
