import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero/hero";
import Homepagelist from "../components/homepagelist/hompagelist";
import { useState, useEffect } from "react";
import Joblist from "../components/homepagelist/joblist";
import Jobcard from "../components/homepagelist/jobcard";

export default function Home({ data }) {
 

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="">
        <Hero />        

        <div className="bg-gray-100 pb-5 flex justify-center">
          <div className=" w-[1190px] flex flex-col justify-center">
            <h1 className="text-3xl text-center font-semibold py-5">
              Discover jobs for you
            </h1>
            <div className="px-5 grid lg:grid-cols-3 md:grid-cols-2 gap-5">
              {data.map((data) => (
                <Jobcard key={data.id} {...data} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(process.env.NEXT_PUBLIC_URL + "/api/jobs?populate=*&pagination[pageSize]=6");  
  const data = await res.json();
  
  return {
    props: { data : data.data },
  };
};
